# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  demo:
    image: demo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5108:5108
